### ISSUE TITLE
blade templates hooks

### ISSUE THREAD

**Issue by neuronetio** [esemve/Hook#1]
There is an error in blade templates documentation.
To listen blade templates we need to listen `template.hookName` instead of just `hookName`

**Comment by esemve** [comment]
Jeah, it's not a bug, its a feature, because i want to separate template hooks and normal hooks

**Comment by neuronetio** [comment]
in documentation there is no clue about this,
we must read source files to get this info
if we don't know about this, template hooks will not work out of the box

**Comment by esemve** [comment]
you right, I will fix it the docs
