### ISSUE TITLE
[feature request] @hook with html content as second parameter

### ISSUE THREAD

**Issue by neuronetio** [esemve/Hook#2]
It will be great to have something like this:
```blade
@hook('some_place')
Some content
@endhook
```
```php
\Hook::listen('template.some_place',function($callback, $output, $variables, $content){
    return $content."haha!";
});
```

**Comment by neuronetio** [comment]
Or `@hookcomponent` `@endhookcomponent` for backward compability

**Comment by esemve** [comment]
That's a really good idea, I might look into it in the future- or if you have the time+energy, looking forward to your pull request :)

**Comment by neuronetio** [comment]
#3

**Comment by esemve** [comment]
Thx a lot! I try it at weekend, after i merge it

**Comment by esemve** [comment]
Thx a lot, I merged it!
