### ISSUE TITLE
listeners overriding?

### ISSUE THREAD

**Issue by neuronetio** [esemve/Hook#4]
Should we override listeners ?

If you have modular application - you don't know on which position your module land in the system.

If you don't specify priority, listeners will be overrided.

If you do, and you may have collision with other module created by other peoples.

Maybe some kind of auto incrementing index will be better approach?

**Comment by neuronetio** [comment]
or from other way... maybe it is good to override listeners...
if there is a system with hooks it should have some kind of mechanism to position listeners like prestashop

**Comment by esemve** [comment]
Yeah, it's a feature :)

**Comment by neuronetio** [comment]
maybe throwing exception when listener already exist will be good idea
you will have confidence that you don't miss anything

**Comment by esemve** [comment]
I think its ok now
