### ISSUE TITLE
Where should I put the listen code

### ISSUE THREAD

**Issue by parse-code** [esemve/Hook#6]
This package is awesome, good job.

One question, what's the best practice of putting the listen code?

Now I put it in middleware, it work fine from the web, but can not access from command line.

**Comment by inbaz** [comment]
I just found this package as well and I got the same question in my mind. So would be great to extend the examples to see where the code is put in.

**Comment by hasnatbabur** [comment]
Hi, I think placing all hook callback functions/class will be good in app/Hooks folder. Thanks.
